name: "Pull Request Labeler"
on: [pull_request]

jobs:
  label:
    runs-on: ubuntu-latest
    stes:
      - uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
